# Generated by Django 4.2.28 on 2026-02-14 17:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(help_text='Human-readable name of the position', max_length=420, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Position',
                'verbose_name_plural': 'Positions',
                'ordering': ['text'],
            },
        ),
        migrations.CreateModel(
            name='TeamArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(help_text='Human-readable name of the team area', max_length=420, verbose_name='Name')),
                ('code', models.CharField(help_text='Short identifier of the team area', max_length=50, unique=True, verbose_name='Code')),
            ],
            options={
                'verbose_name': 'Team area',
                'verbose_name_plural': 'Team areas',
                'ordering': ['text'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('professional_wiki_handle', models.CharField(blank=True, default='', max_length=50, verbose_name='Professional username')),
                ('personal_wiki_handle', models.CharField(blank=True, default='', max_length=50, verbose_name='Personal username')),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('non_binary', 'Non Binary'), ('other', 'Other'), ('not_declared', 'Not declared')], default='not_declared', max_length=20, verbose_name='Gender')),
                ('photograph', models.CharField(blank=True, default='', max_length=420, verbose_name='Photograph filename')),
                ('twitter', models.CharField(blank=True, default='', help_text='Twitter handle', max_length=100, verbose_name='Twitter')),
                ('facebook', models.CharField(blank=True, default='', help_text='Facebook handle', max_length=100, verbose_name='Facebook')),
                ('instagram', models.CharField(blank=True, default='', help_text='Instagram handle', max_length=100, verbose_name='Instagram')),
                ('wikidata_item', models.CharField(blank=True, default='', help_text='Wikidata QID', max_length=100, verbose_name='Wikidata item')),
                ('linkedin', models.CharField(blank=True, default='', help_text='LinkedIn handle', max_length=100, verbose_name='LinkedIn')),
                ('orcid', models.CharField(blank=True, default='', help_text='ORCID ID', max_length=100, verbose_name='ORCID')),
                ('position', models.ForeignKey(blank=True, help_text='The position this user belongs to', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users', to='users.position', verbose_name='Position')),
                ('user', models.OneToOneField(help_text="The user which this profile's about", on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'User profile',
                'verbose_name_plural': 'User profiles',
            },
        ),
        migrations.AddField(
            model_name='position',
            name='area_associated',
            field=models.ForeignKey(help_text='The team area this position belongs to', on_delete=django.db.models.deletion.PROTECT, related_name='positions', to='users.teamarea', verbose_name='Team Area'),
        ),
        migrations.AddField(
            model_name='position',
            name='type',
            field=models.ForeignKey(help_text='The permission group this position belongs to', on_delete=django.db.models.deletion.PROTECT, to='auth.group', verbose_name='Permission group'),
        ),
        migrations.AlterUniqueTogether(
            name='position',
            unique_together={('area_associated', 'text')},
        ),
    ]
