# Generated by Django 6.0.2 on 2026-02-09 22:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Evento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(max_length=200, verbose_name="Nombre del evento"),
                ),
                ("fecha_inicio", models.DateTimeField(verbose_name="Fecha de inicio")),
                ("fecha_fin", models.DateTimeField(verbose_name="Fecha de fin")),
                (
                    "area_responsable",
                    models.CharField(max_length=100, verbose_name="Área responsable"),
                ),
                (
                    "participantes_esperados",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Participantes esperados",
                    ),
                ),
                (
                    "descripcion",
                    models.TextField(blank=True, verbose_name="Descripción"),
                ),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Evento",
                "verbose_name_plural": "Eventos",
                "ordering": ["fecha_inicio"],
            },
        ),
    ]
