# Generated by Django 6.0.2 on 2026-02-12 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="evento",
            name="fecha_fin",
            field=models.DateField(verbose_name="Fecha de fin"),
        ),
        migrations.AlterField(
            model_name="evento",
            name="fecha_inicio",
            field=models.DateField(verbose_name="Fecha de inicio"),
        ),
    ]
