# Generated by Django 5.2.11 on 2026-03-11 17:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_rename_evento_to_event_and_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=200, verbose_name="Nombre del proyecto"
                    ),
                ),
                (
                    "program",
                    models.CharField(
                        choices=[
                            ("ASC", "Apropiación social de conocimiento"),
                            ("TC", "Tecnologías y comunidades"),
                        ],
                        max_length=3,
                        verbose_name="Programa",
                    ),
                ),
                ("start_date", models.DateField(verbose_name="Fecha de inicio")),
                ("end_date", models.DateField(verbose_name="Fecha de fin")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Descripción"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planning", "Planeación"),
                            ("active", "Activo"),
                            ("paused", "En pausa"),
                            ("finished", "Finalizado"),
                        ],
                        default="planning",
                        max_length=20,
                    ),
                ),
                (
                    "responsible",
                    models.CharField(max_length=150, verbose_name="Responsable"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Proyecto",
                "verbose_name_plural": "Proyectos",
                "ordering": ["-start_date"],
            },
        ),
        migrations.AlterModelOptions(
            name="event",
            options={
                "ordering": ["start_date"],
                "verbose_name": "Evento",
                "verbose_name_plural": "Eventos",
            },
        ),
        migrations.CreateModel(
            name="Activity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        max_length=200, verbose_name="Nombre de la actividad"
                    ),
                ),
                ("fecha", models.DateField(verbose_name="Fecha de la actividad")),
                (
                    "descripcion",
                    models.TextField(blank=True, verbose_name="Descripción"),
                ),
                (
                    "participantes",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Participantes"
                    ),
                ),
                (
                    "participantes_verificacion",
                    models.TextField(
                        blank=True, verbose_name="Links o verificación de participantes"
                    ),
                ),
                (
                    "personas_alcanzadas",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Personas alcanzadas indirectamente"
                    ),
                ),
                (
                    "personas_alcanzadas_verificacion",
                    models.TextField(
                        blank=True,
                        verbose_name="Links o verificación de personas alcanzadas",
                    ),
                ),
                (
                    "contenidos_creados",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Contenidos creados"
                    ),
                ),
                (
                    "contenidos_creados_verificacion",
                    models.TextField(
                        blank=True,
                        verbose_name="Links o verificación de contenidos creados",
                    ),
                ),
                (
                    "recursos_educativos_abiertos",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Recursos educativos abiertos"
                    ),
                ),
                (
                    "recursos_educativos_abiertos_verificacion",
                    models.TextField(
                        blank=True,
                        verbose_name="Links o verificación de recursos educativos abiertos",
                    ),
                ),
                (
                    "productos",
                    models.PositiveIntegerField(default=0, verbose_name="Productos"),
                ),
                (
                    "productos_verificacion",
                    models.TextField(
                        blank=True, verbose_name="Links o verificación de productos"
                    ),
                ),
                (
                    "instituciones_participantes",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Instituciones participantes"
                    ),
                ),
                (
                    "instituciones_participantes_verificacion",
                    models.TextField(
                        blank=True,
                        verbose_name="Links o verificación de instituciones participantes",
                    ),
                ),
                (
                    "alianzas_estrategicas",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Alianzas estratégicas"
                    ),
                ),
                (
                    "alianzas_estrategicas_verificacion",
                    models.TextField(
                        blank=True,
                        verbose_name="Links o verificación de alianzas estratégicas",
                    ),
                ),
                (
                    "historias",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Historias sobre soluciones y desafíos"
                    ),
                ),
                (
                    "historias_verificacion",
                    models.TextField(
                        blank=True, verbose_name="Links o verificación de historias"
                    ),
                ),
                (
                    "sostenibilidad",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Sostenibilidad"
                    ),
                ),
                (
                    "sostenibilidad_verificacion",
                    models.TextField(
                        blank=True,
                        verbose_name="Links o verificación de sostenibilidad",
                    ),
                ),
                (
                    "numero_editores",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Número total de editores"
                    ),
                ),
                (
                    "numero_editores_verificacion",
                    models.TextField(
                        blank=True, verbose_name="Links o verificación de editores"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "proyecto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to="core.project",
                        verbose_name="Proyecto",
                    ),
                ),
            ],
            options={
                "verbose_name": "Actividad",
                "verbose_name_plural": "Actividades",
                "ordering": ["-fecha"],
            },
        ),
    ]
