# Generated by Django 4.2.28 on 2026-03-10 21:04

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_evento_to_event_and_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['start_date'], 'verbose_name': 'Evento', 'verbose_name_plural': 'Eventos'},
        ),
        migrations.AddField(
            model_name='event',
            name='activity_type',
            field=models.CharField(blank=True, choices=[('workshop', 'Taller de formación'), ('conference', 'Charla/Conferencia'), ('comunity_event', 'Encuentro comunitario'), ('educational_program', 'Programa educativo'), ('other', 'Otro')], max_length=20, verbose_name='Tipo de actividad'),
        ),
        migrations.AddField(
            model_name='event',
            name='attendance_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identificador único usado para registrar asistencias.', null=True, unique=True, verbose_name='Token de asistencia'),
        ),
        migrations.AddField(
            model_name='event',
            name='location',
            field=models.CharField(blank=True, choices=[('bogota', 'Bogotá'), ('andina', 'Región Andina'), ('orinoquia', 'Región Orinoquía'), ('pacifico', 'Región Pacífico'), ('amazonia', 'Región Amazónica'), ('caribe', 'Región Caribe'), ('virtual', 'Virtual')], max_length=150, verbose_name='Ubicación donde se realizó el evento'),
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nombre')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo electrónico')),
                ('wiki_username', models.CharField(blank=True, max_length=150, verbose_name='Usuario de Wikipedia')),
                ('department', models.CharField(blank=True, max_length=150, verbose_name='Departamento donde se realizó el evento')),
                ('satisfaction', models.PositiveSmallIntegerField(help_text='Indique su nivel de satisfacción en una escala de 1 a 5.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Satisfacción (1-5)')),
                ('comments', models.TextField(blank=True, verbose_name='Comentarios')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='core.event', verbose_name='Evento')),
            ],
            options={
                'verbose_name': 'Asistencia',
                'verbose_name_plural': 'Asistencias',
                'ordering': ['-created_at'],
            },
        ),
    ]
