# Generated by Django 4.2.28 on 2026-03-11 19:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_event_options_event_activity_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='attendance_mode',
            field=models.CharField(choices=[('presential', 'Presencial'), ('virtual', 'Virtual')], default=django.utils.timezone.now, max_length=20, verbose_name='Modo de asistencia'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='attendance',
            name='department',
            field=models.CharField(blank=True, choices=[('amazonas', 'Amazonas'), ('antioquia', 'Antioquia'), ('arauca', 'Arauca'), ('atlantico', 'Atlántico'), ('bolivar', 'Bolívar'), ('boyaca', 'Boyacá'), ('caldas', 'Caldas'), ('caqueta', 'Caquetá'), ('casanare', 'Casanare'), ('cauca', 'Cauca'), ('cesar', 'Cesar'), ('choco', 'Chocó'), ('cordoba', 'Córdoba'), ('cundinamarca', 'Cundinamarca'), ('bogota', 'Distrito Capital (Bogotá)'), ('guainia', 'Guainía'), ('guaviare', 'Guaviare'), ('huila', 'Huila'), ('laguajira', 'La Guajira'), ('magdalena', 'Magdalena'), ('meta', 'Meta'), ('narino', 'Nariño'), ('nortesantander', 'Norte de Santander'), ('putumayo', 'Putumayo'), ('quindio', 'Quindío'), ('risaralda', 'Risaralda'), ('santander', 'Santander'), ('sucre', 'Sucre'), ('tolima', 'Tolima'), ('valle', 'Valle del Cauca'), ('vaupes', 'Vaupés'), ('vichada', 'Vichada')], max_length=150, verbose_name='Departamento al que pertenece'),
        ),
    ]
