# Generated by Django 5.2.11 on 2026-03-12 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_project_alter_event_options_activity"),
        ("core", "0005_attendance_attendance_mode_and_more"),
    ]

    operations = []
