# Generated by Django 5.2.11 on 2026-03-17 19:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_merge_20260311_2033"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="proyecto",
            field=models.ForeignKey(
                blank=True,
                help_text="Proyecto asociado a este evento.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="events",
                to="core.project",
                verbose_name="Proyecto",
            ),
        ),
    ]
