# Generated by Django 5.2.11 on 2026-03-26 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_event_proyecto"),
    ]

    operations = [
        migrations.AddField(
            model_name="activity",
            name="area",
            field=models.CharField(
                blank=True,
                choices=[
                    ("bogota", "Bogotá"),
                    ("andina", "Región Andina"),
                    ("orinoquia", "Región Orinoquía"),
                    ("pacifico", "Región Pacífico"),
                    ("amazonia", "Región Amazónica"),
                    ("caribe", "Región Caribe"),
                    ("virtual", "Virtual"),
                ],
                max_length=150,
                verbose_name="Área donde se realizó la actividad",
            ),
        ),
    ]
