# Generated by Django 5.2.11 on 2026-04-01 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_rename_activity_fields"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="activity",
            options={
                "ordering": ["-date"],
                "verbose_name": "Actividad",
                "verbose_name_plural": "Actividades",
            },
        ),
        migrations.AlterField(
            model_name="activity",
            name="area",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ASC", "Apropiación social de conocimiento"),
                    ("TC", "Tecnologías y comunidades"),
                ],
                max_length=3,
                verbose_name="Área de la actividad",
            ),
        ),
    ]
