# Generated by Django 5.2.11 on 2026-04-01 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_alter_activity_options_alter_activity_area"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activity",
            name="area",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ASC", "Apropiación social de conocimiento"),
                    ("TC", "Tecnologías y comunidades"),
                    ("DA", "Dirección Administrativa"),
                ],
                max_length=3,
                verbose_name="Área de la actividad",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="program",
            field=models.CharField(
                choices=[
                    ("ASC", "Apropiación social de conocimiento"),
                    ("TC", "Tecnologías y comunidades"),
                    ("DA", "Dirección Administrativa"),
                ],
                max_length=3,
                verbose_name="Programa",
            ),
        ),
    ]
