# Generated by Django 5.2.11 on 2026-04-02 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_alter_activity_area_alter_project_program"),
    ]

    operations = [
        migrations.AddField(
            model_name="activity",
            name="event_participation",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Participación en eventos"
            ),
        ),
        migrations.AddField(
            model_name="activity",
            name="event_participation_verification",
            field=models.TextField(
                blank=True,
                verbose_name="Links o verificación de participación en eventos",
            ),
        ),
    ]
